config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  root :to => 'home#index'

  resources :users_admin, :controller => "users"
  resources :sectors
  resources :materials
  resources :units
end

app/models/material.rb
class Material < ActiveRecord::Base
  validates :description, presence: true
  validates :description, uniqueness: true, on: :create

  ransacker :id do
    Arel.sql("to_char(id, '9999999')")
  end
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true, on: :create

  ransacker :id do
    Arel.sql("to_char(id, '9999999')")
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :description, presence: true
  validates :description, uniqueness: true, on: :create

  ransacker :id do
    Arel.sql("to_char(id, '9999999')")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  attr_accessor :login
  validate :validate_username
  validates :email, :presence => true

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false}

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  respond_to :html, :xml, :json

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
    @q = Material.search(params[:q])
    @materials = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10 )
    respond_with @materials
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    @material.save
    respond_with @material, location: materials_path
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    @material = Material.find(params[:id])

    @material.update_attributes(material_params)
    respond_with @material, location: materials_path
  end

  def destroy
    @material = Material.find(params[:id])
    @material.destroy
    respond_with @material
  end

  private

  def material_params
    params.require(:material).permit(:description)
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  def index
    @q = Sector.search(params[:q])
    @sectors = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10 )
    respond_with @sectors
  end

  def new
    @sector = Sector.new
  end

  def create
    @sector = Sector.new(sector_params)
    @sector.save
    respond_with @sector, location: sectors_path
  end

  def edit
    @sector = Sector.find(params[:id])
  end

  def update
    @sector = Sector.find(params[:id])

    @sector.update_attributes(sector_params)
    respond_with @sector, location: sectors_path
  end

  def destroy
    @sector = Sector.find(params[:id])
    @sector.destroy
    respond_with @sector
  end

  private

  def sector_params
    params.require(:sector).permit(:name)
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @q = Unit.search(params[:q])
    @units = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10 )
    respond_with @units
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    @unit.save
    respond_with @unit, location: units_path
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])

    @unit.update_attributes(unit_params)
    respond_with @unit, location: units_path
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    respond_with @unit
  end

  private

  def unit_params
    params.require(:unit).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.search(params[:q])
    @users = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10 )
    respond_with @users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with @user, location: users_admin_index_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

    @user.update_attributes(user_params)
    respond_with @user, location: users_admin_index_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name)
    params[:controller] == controller_name ? "active" : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? "active" : nil
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Juarez Lustosa
    </div>
    <div>
        <strong>Copyright</strong> LooP Solutions &copy; 2016
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <span>
            <img alt="image" class="img-circle" src="<%= image_url 'profile_small.jpg' %>"/>
          </span>
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
              <span class="block m-t-xs">
                <strong class="font-bold">Fernando Almeida</strong>
              </span> <span class="text-muted text-xs block">Administrador <b class="caret"></b></span>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a href="">Profile</a></li>
            <li><a href="">Contacts</a></li>
            <li><a href="">Mailbox</a></li>
            <li class="divider"></li>
            <li>
              <% if current_user %>
                <%= link_to "Deslogar", destroy_user_session_path, :method=>'delete' %>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="logo-element">
          CCIH
        </div>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-th-large"></i>
          <span class="nav-label">Administração</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Usuários", users_admin_index_path %></li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label">Cadastros Básicos</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li><%= link_to "Serviços", sectors_path %></li>
          <li class="<%= is_active_action('advanced') %>"><%= link_to "Unidades", units_path %> </li>
          <li class="<%= is_active_action('wizard') %>"><%= link_to "Material", materials_path %> </li>
          <li class="<%= is_active_action('file_upload') %>"><%= link_to "Fatores de Risco", root_path %> </li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-users"></i>
          <span class="nav-label" data-i18n="nav.forms">Cadastro de Pessoas</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Pacientes", root_path %></li>
          <li class="<%= is_active_action('advanced') %>"><%= link_to "Profissionais", root_path %> </li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label" data-i18n="nav.forms">Cirurgias</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Cirurgias", root_path %></li>
          <li class="<%= is_active_action('advanced') %>"><%= link_to "Procedimentos", root_path %> </li>
          <li class="<%= is_active_action('wizard') %>"><%= link_to "Sítio Principal", root_path %> </li>
          <li class="<%= is_active_action('file_upload') %>"><%= link_to "Sítio Específico", root_path %> </li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label" data-i18n="nav.forms">Micro-organismos</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Grupo", root_path %></li>
          <li class="<%= is_active_action('advanced') %>"><%= link_to "Classe", root_path %> </li>
          <li class="<%= is_active_action('wizard') %>"><%= link_to "Espécie", root_path %> </li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label" data-i18n="nav.forms">Antimicrobianos</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Classe", root_path %></li>
          <li class="<%= is_active_action('advanced') %>"><%= link_to "Subclasse", root_path %> </li>
          <li class="<%= is_active_action('wizard') %>"><%= link_to "Antimicrobianos", root_path %> </li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label" data-i18n="nav.forms">Hemodiálise</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Infecções", root_path %></li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label" data-i18n="nav.forms">Microbiologia</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Infecções e Microbiologia", root_path %></li>
        </ul>
      </li>

      <li class="<%= is_active_controller('forms') %>">
        <a href="#"><i class="fa fa-edit"></i>
          <span class="nav-label" data-i18n="nav.forms">Denominadores</span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('forms') %>">
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Ficha Uti Neonatal", root_path %></li>
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Ficha Uti Adulto", root_path %></li>
          <li class="<%= is_active_action('basic_forms') %>"><%= link_to "Ficha de componente cirúrgico", root_path %></li>
        </ul>
      </li>

      <li class="<%= is_active_controller('graphs') %>">
        <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label" data-i18n="nav.graphs">Graficos</span><span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse <%= is_active_controller('graphs') %>">
          <li class="<%= is_active_action('flot') %>"><%= link_to "Flot Charts", root_path %></li>
          <li class="<%= is_active_action('morris') %>"><%= link_to "Morris.js Charts", root_path %></li>
          <li class="<%= is_active_action('rickshaw') %>"><%= link_to "Rickshaw Charts", root_path %> </li>
          <li class="<%= is_active_action('chartjs') %>"><%= link_to "Chart.js", root_path %></li>
          <li class="<%= is_active_action('chartist') %>"><%= link_to "Chartist", root_path %></li>
          <li class="<%= is_active_action('c3charts') %>"><%= link_to "c3 charts", root_path %></li>
          <li class="<%= is_active_action('peity') %>"><%= link_to "Peity Charts", root_path %></li>
          <li class="<%= is_active_action('sparkline') %>"><%= link_to "Sparkline Charts", root_path %> </li>
        </ul>
      </li>

      <li class="landing_link">
        <%= link_to root_path do %>
        <i class="fa fa-star"></i> <span class="nav-label" data-i18n="nav.landing">Página SisCCIH </span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/materials/_materials.html.erb
<table class="table table-hover" id="materials">
  <tbody>
    <% @materials.each do |material| %>
      <tr>

        <td class="project-title">
          <span class="badge badge-info">Código <%= material.id %></span>
        </td>

        <td class="contact-type"><i class="fa fa-building-o"> </i></td>
        <td class="project-badge title">
          <%= link_to "#{material.description}", materials_path%>
          <br />
          <small>Criado em <%=l material.created_at %></small>
        </td>

        <td class="project-actions">
          <%= link_to edit_material_path(material), class: "btn btn-white btn-sm" do %>
            <i class="fa fa-pencil"></i> Editar
          <% end %>
        </td>

        <td class="project-actions">
          <%= link_to material,
                class: "btn btn-white btn-sm",
                method: :delete,
                data: { confirm: "Tem certeza que deseja apagar"} do %>
            <i class="fa fa-trash"></i> Apagar
          <% end %>
        </td>
      </tr>
    <% end %>
    <% unless @materials.any? %>
      <div class="ibox-content">
        <div class="alert alert-warning">
          Nenhum material encontrado, deseja <%= link_to "Cadastrar", new_material_path %> ?
        </div>
      </div>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="6">
        <ul class="pagination pull-right">
          <%= will_paginate @materials, renderer: BootstrapPagination::Rails %>
        </ul>
      </td>
    </tr>
  </tfoot>

</table>

app/views/materials/index.html.erb
<%= render "header" %>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Lista de todos os materiais registrados</h5>
          <div class="ibox-tools">
            <%= link_to "Cadastrar materiais", new_material_path, class: "btn btn-primary btn-xs" %>
          </div>
        </div>

        <div class="ibox-content">
          <div class="row m-b-sm m-t-sm">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
              <div class="search-form">
                  <%= search_form_for @q,
                      :builder => SimpleForm::FormBuilder,
                      wrapper: :horizontal_form,
                      html: { class: "form-horizontal" } do |f| %>

                    <div class="form-group">
                      <div class="input-group m-b">
                        <span class="input-group-btn">
                          <%= link_to "Refresh", materials_path, class: "btn btn-sm btn-primary" %>
                        </span>
                        <%= f.input_field :description_or_id_cont, placeholder: "Pesquisar pelo material ou pelo código", class: "form-control input-sm" %>
                        <span class="input-group-btn">
                          <%= f.button :submit, "Pesquisar", class: "btn btn-sm btn-primary" %>
                        </span>
                      </div>
                    </div>
                  <div class="hr-line-dashed"></div>
                  <% end %>
              </div>
            </div>
          </div>
          <div class="project-list">
            <%= render partial: "materials" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sectors/_sectors.html.erb
<table class="table table-hover" id="sectors">
  <tbody>
    <% @sectors.each do |sector| %>
      <tr>

        <td class="project-title">
          <span class="badge badge-info">Código <%= sector.id %></span>
        </td>

        <td class="contact-type"><i class="fa fa-building-o"> </i></td>
        <td class="project-badge title">
          <%= link_to "#{sector.name}", sectors_path%>
          <br />
          <small>Criado em <%=l sector.created_at %></small>
        </td>

        <td class="project-actions">
          <%= link_to edit_sector_path(sector), class: "btn btn-white btn-sm" do %>
            <i class="fa fa-pencil"></i> Editar
          <% end %>
        </td>

        <td class="project-actions">
          <%= link_to sector,
                class: "btn btn-white btn-sm",
                method: :delete,
                data: { confirm: "Tem certeza que deseja apagar"} do %>
            <i class="fa fa-trash"></i> Apagar
          <% end %>
        </td>
      </tr>
    <% end %>
    <% unless @sectors.any? %>
      <div class="ibox-content">
        <div class="alert alert-warning">
          Nenhum serviço encontrado, deseja <%= link_to "Cadastrar", new_sector_path %> ?
        </div>
      </div>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="6">
        <ul class="pagination pull-right">
          <%= will_paginate @sectors, renderer: BootstrapPagination::Rails %>
        </ul>
      </td>
    </tr>
  </tfoot>

</table>

app/views/sectors/index.html.erb
<%= render "header" %>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Lista de todos os serviços registrados</h5>
          <div class="ibox-tools">
            <%= link_to "Cadastrar serviços", new_sector_path, class: "btn btn-primary btn-xs" %>
          </div>
        </div>

        <div class="ibox-content">
          <div class="row m-b-sm m-t-sm">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
              <div class="search-form">
                  <%= search_form_for @q,
                      :builder => SimpleForm::FormBuilder,
                      wrapper: :horizontal_form,
                      html: { class: "form-horizontal" } do |f| %>

                    <div class="form-group">
                      <div class="input-group m-b">
                        <span class="input-group-btn">
                          <%= link_to "Refresh", sectors_path, class: "btn btn-sm btn-primary" %>
                        </span>
                        <%= f.input_field :name_or_id_cont, placeholder: "Pesquisar pelo nome do serviço ou pelo código", class: "form-control input-sm" %>
                        <span class="input-group-btn">
                          <%= f.button :submit, "Pesquisar", class: "btn btn-sm btn-primary" %>
                        </span>
                      </div>
                    </div>
                  <div class="hr-line-dashed"></div>
                  <% end %>
              </div>
            </div>
          </div>
          <div class="project-list">
            <%= render partial: "sectors" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/units/_units.html.erb
<table class="table table-hover" id="units">
  <tbody>
    <% @units.each do |unit| %>
      <tr>

        <td class="project-title">
          <span class="badge badge-info">Código <%= unit.id %></span>
        </td>

        <td class="contact-type"><i class="fa fa-building-o"> </i></td>
        <td class="project-badge title">
          <%= link_to "#{unit.description}", units_path%>
          <br />
          <small>Criado em <%=l unit.created_at %></small>
        </td>

        <td class="project-actions">
          <%= link_to edit_unit_path(unit), class: "btn btn-white btn-sm" do %>
            <i class="fa fa-pencil"></i> Editar
          <% end %>
        </td>

        <td class="project-actions">
          <%= link_to unit,
                class: "btn btn-white btn-sm",
                method: :delete,
                data: { confirm: "Tem certeza que deseja apagar"} do %>
            <i class="fa fa-trash"></i> Apagar
          <% end %>
        </td>
      </tr>
    <% end %>
    <% unless @units.any? %>
      <div class="ibox-content">
        <div class="alert alert-warning">
          Nenhuma unidade encontrada, deseja <%= link_to "Cadastrar", new_unit_path %> ?
        </div>
      </div>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="6">
        <ul class="pagination pull-right">
          <%= will_paginate @units, renderer: BootstrapPagination::Rails %>
        </ul>
      </td>
    </tr>
  </tfoot>
</table>

app/views/units/edit.html.erb
<%= render "form" %>

app/views/units/index.html.erb
<%= render "header" %>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Lista de todas as unidades registradas</h5>
          <div class="ibox-tools">
            <%= link_to "Cadastrar unidades", new_unit_path, class: "btn btn-primary btn-xs" %>
          </div>
        </div>

        <div class="ibox-content">
          <div class="row m-b-sm m-t-sm">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
              <div class="search-form">
                  <%= search_form_for @q,
                      :builder => SimpleForm::FormBuilder,
                      wrapper: :horizontal_form,
                      html: { class: "form-horizontal" } do |f| %>

                    <div class="form-group">
                      <div class="input-group m-b">
                        <span class="input-group-btn">
                          <%= link_to "Refresh", units_path, class: "btn btn-sm btn-primary" %>
                        </span>
                        <%= f.input_field :description_or_id_cont, placeholder: "Pesquisar pela unidade ou pelo código", class: "form-control input-sm" %>
                        <span class="input-group-btn">
                          <%= f.button :submit, "Pesquisar", class: "btn btn-sm btn-primary" %>
                        </span>
                      </div>
                    </div>
                  <div class="hr-line-dashed"></div>
                  <% end %>
              </div>
            </div>
          </div>
          <div class="project-list">
            <%= render partial: "units" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_users.html.erb
<table class="table table-hover">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="project-status">
          <span class="label label-primary">Ativo</span>
        </td>
        <td class="contact-type"><i class="fa fa-user"> </i></td>
        <td class="project-title">
        <%= link_to "#{user.username}", users_admin_path(user)%>
        <br />
        <small>Criado em <%=l user.created_at %></small>
        </td>

        <td class="contact-type"><i class="fa fa-envelope"> </i></td>
        <td> <%= user.email %></td>

        <td class="project-actions">
          <%= link_to edit_users_admin_path(user), class: "btn btn-white btn-sm" do %>
            <i class="fa fa-pencil"></i> Editar
          <% end %>
        </td>
      </tr>
    <% end %>
    <% unless @users.any? %>
      <div class="ibox-content">
        <div class="alert alert-warning">
          Infelizmente não foram encontrado usuários com esse nome.
        </div>
      </div>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="6">
        <ul class="pagination pull-right">
          <%= will_paginate @users , renderer: BootstrapPagination::Rails %>
        </ul>
      </td>
    </tr>
  </tfoot>

</table>

app/views/users/index.html.erb
<%= render "header" %>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Lista de todos os usuários registrados</h5>
          <div class="ibox-tools">
            <%= link_to "Cadastrar Usuário", new_users_admin_path, class: "btn btn-primary btn-xs" %>
          </div>
        </div>

        <div class="ibox-content">
          <div class="row m-b-sm m-t-sm">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
              <div class="search-form">
                  <%= search_form_for @q,
                      url: users_admin_index_path,
                      :builder => SimpleForm::FormBuilder,
                      wrapper: :horizontal_form,
                      html: { class: "form-horizontal" } do |f| %>

                    <div class="form-group">
                      <div class="input-group m-b">
                        <span class="input-group-btn">
                          <%= link_to "Refresh", users_admin_index_path, class: "btn btn-sm btn-primary" %>
                        </span>
                        <%= f.input_field :username_cont, placeholder: "Pesquisar pelo usuário", class: "form-control input-sm" %>
                        <span class="input-group-btn">
                          <%= f.button :submit, "Pesquisar", class: "btn btn-sm btn-primary" %>
                        </span>
                      </div>
                    </div>
                  <div class="hr-line-dashed"></div>
                  <% end %>
              </div>
            </div>
          </div>
          <div class="project-list">
            <%= render partial: "users" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>